version: 2
jobs:
  run-tests:
    docker:
      - image: node:8.11.3
    steps:
      - checkout
      - run:
          name: Test generator-playsonapi yeoman project 
          command: |
            cd generator-playsonapi
            npm install .
            npm test
            cd ..
            ./test.sh -d
          no_output_timeout: 5m
workflows:
  version: 2
  run-playsonapi-tests:
    jobs:
      - run-tests
