version: 2
jobs:
  run-scaffold-tests:
    docker:
      - image: node:8.11.3
    steps:
      - checkout
      - run:
          name: Test generator-playsonapi yeoman project 
          command: |
            cd generator-playsonapi
            npm install .
            npm test
          no_output_timeout: 5m
  run-integration-tests:
    steps:
      - checkout
      - run:
          name: Test sbt project
          command: |
            ./test.sh
workflows:
  version: 2
  run-scaffold-tests:
    jobs:
      - run-scaffold-tests
